with

renamed as (
    select
        id as user_contract_id,
        created_at,
        updated_at,
        location_id,
        contract_end,
        contract_time,
        contract_start,
        contract_end_trial,
        contract_type,
        lastname as user_contract_lastname,
        firstname as user_contract_firstname,
        street_address as user_contract_street_address,
        do_not_show_in_register,
        contract_end_reason,
        team_id,
        invitation_sent_at,
        invitation_accepted_at,
        membership_id,
        daily_worker,
        working_days_in_week,
        partner_id,
        birth_department_code,
        start_time,
        account_id,
        original_contract_id,
        type as user_contract_type,
        virtual
    from {{ source('sources', 'user_contracts') }}
)

select
    user_contract_id,
    created_at,
    updated_at,
    location_id,
    contract_end,
    contract_time,
    contract_start,
    contract_end_trial,
    contract_type,
    user_contract_lastname,
    user_contract_firstname,
    user_contract_street_address,
    do_not_show_in_register,
    contract_end_reason,
    team_id,
    invitation_sent_at,
    invitation_accepted_at,
    membership_id,
    daily_worker,
    working_days_in_week,
    partner_id,
    birth_department_code,
    start_time,
    account_id,
    original_contract_id,
    user_contract_type,
    virtual
from renamed